### ISSUE TITLE
OAuth token for each LISTEN

### ISSUE THREAD

**Issue by Shagrat2** [theorx/go-ttv-pubsub#1]
I need to subscribe to different channels with their OAuth

**Comment by theorx** [comment]
@Shagrat2 For that you will need to create separate instances of the client. Twitch API works on per connection basis, for each socket opened you will need to authenticate separately. 

```
channel1 := TTVClient.CreateClient("your-access_token1", TTVClient.TwitchPubSubHost)
channel2 := TTVClient.CreateClient("your-access_token2", TTVClient.TwitchPubSubHost)
channel3 := TTVClient.CreateClient("your-access_token3", TTVClient.TwitchPubSubHost)

//And then Subscribe() to each as needed
```

In order to get the access token, you must go through the OAuth flow, but this library does not cover that, you would have to implement that on your own. Basically you could either just do it manually by creating a twitch APP with your endpoint so you would authenticate using OAuth to capture the authentication token or you could just send the requests manually using Curl.
